### ISSUE TITLE
[Anon] Orc and Goblin Tribes - Nomadic Waaagh!: The Nomadic Waaagh list does not count orc boy mobs correctly.

### ISSUE THREAD

**Issue by NewRecruitAnon** [vflam/Warhammer-The-Old-World#44]
**Problem:**
The Nomadic Waaagh list does not count orc boy mobs correctly.

**Expected:**
With an orc warboss as general, 1 unit of orc boar boys may be taken as Core, but you may still take as many boar boys units as Special as desired. Currently, New Recruit flags you for taking anything more than 1 unit regardless of which slot its fielded in the muster list.

 **Additional Info:**
See Arcane Journal 'Nomadic Waaagh' list.

**List:** https://www.newrecruit.eu/app/list/jRftO
**Unit:** Orc Boar Chariots[2], id: a679-52-9e65-9499

**Comment by Tidomann** [comment]
It is not counting the Orc Board Boy Mobs-

It is counting the unit options added to them. Since the list is 1500 points the following only allows for one orc boar boy mob to take it.

- 0-1 unit per 1,000 points may:
-- Replace light armour ....
-- Purchase a magic standard....

In the list provided, the unit option toggle was selected twice, exceeding the 1 limit you would have
