### ISSUE TITLE
[Anon] Orc and Goblin Tribes: Black orcs, command options appear as additional models rather than upgrades. 5 models + command will result in 8 models rather than 2 models + 3 command

### ISSUE THREAD

**Issue by NewRecruitAnon** [vflam/Warhammer-The-Old-World#58]
**Problem:**
Black orcs, command options appear as additional models rather than upgrades. 5 models + command will result in 8 models rather than 2 models + 3 command

**Expected:**
5 models + command will result in 8 models rather than 2 models + 3 command

 **Additional Info:**
Orcs and goblins tribes

**List:** https://www.newrecruit.eu/app/list/wrYN5

**Comment by Tidomann** [comment]
Working as intended currently.

Because black orcs are motley crew the equipment of command models needs to be clearly defined. The output on pdf and text is correct. Adding a command model will reduce the required amount of regular troops- which also leads to their increased cost of 18 points each.

Until a better method of champions exist via association
