### ISSUE TITLE
[Anon] Beastmen Brayherds: Minotaur Command adds to the number of models instead, no unit of three possible

### ISSUE THREAD

**Issue by NewRecruitAnon** [vflam/Warhammer-The-Old-World#73]
**Problem:**
Minotaur Command adds to the number of models instead, no unit of three possible

**Expected:**
The number of models shouldn’t change when adding command.

**List:** https://www.newrecruit.eu/app/list/hAxUw
**Unit:** Minotaur Herds, id: 3a01-7d07-ac2a-d5f4

**Comment by Tidomann** [comment]
Command models add to the model count due to the motley crew rule and allowing every model to have a specific loadout. currently unable to attain via Associations.

Adding a command model does reduce the minimum model count- allowing you to properly adjust
![image](https://github.com/user-attachments/assets/10690972-9caf-43a6-94be-21fa5438085b)
